#!/bin/env bash

# Uses invidio.us to search for youtube videos and then streams them
# in mpv from youtube
# Author: Jorde Singh Kang<jorde@protonmail.ch>
# License: GPLv3

[ -v $1 ] || \
curl -s "https://invidio.us/search?q=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$1")" | \
	grep '<a .*href="/watch.*">.*$' | \
	grep -o '"/watch.*"\|<a.*>.*</a>' | \
	sed "s/<[^>]*>//g" | \
	tr -d '"' | \
	sed -e 'N;s/\n/ /' | perl -MHTML::Entities -pe 'decode_entities($_);' | \
        fzf | \
	cut -f1 -d' ' | \
	sed 's/^/https:\/\/youtu.be/g' | \
	xargs mpv $2 \
&& echo "Usage:   \$ yt-search <search term> <mpv options>"


